create table "public"."product_snapshot" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "asin" text not null,
    "final_price" double precision not null
);


alter table "public"."product_snapshot" enable row level security;

CREATE UNIQUE INDEX product_snapshot_pkey ON public.product_snapshot USING btree (id);

alter table "public"."product_snapshot" add constraint "product_snapshot_pkey" PRIMARY KEY using index "product_snapshot_pkey";

alter table "public"."product_snapshot" add constraint "product_snapshot_asin_fkey" FOREIGN KEY (asin) REFERENCES products(asin) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."product_snapshot" validate constraint "product_snapshot_asin_fkey";

grant delete on table "public"."product_snapshot" to "anon";

grant insert on table "public"."product_snapshot" to "anon";

grant references on table "public"."product_snapshot" to "anon";

grant select on table "public"."product_snapshot" to "anon";

grant trigger on table "public"."product_snapshot" to "anon";

grant truncate on table "public"."product_snapshot" to "anon";

grant update on table "public"."product_snapshot" to "anon";

grant delete on table "public"."product_snapshot" to "authenticated";

grant insert on table "public"."product_snapshot" to "authenticated";

grant references on table "public"."product_snapshot" to "authenticated";

grant select on table "public"."product_snapshot" to "authenticated";

grant trigger on table "public"."product_snapshot" to "authenticated";

grant truncate on table "public"."product_snapshot" to "authenticated";

grant update on table "public"."product_snapshot" to "authenticated";

grant delete on table "public"."product_snapshot" to "service_role";

grant insert on table "public"."product_snapshot" to "service_role";

grant references on table "public"."product_snapshot" to "service_role";

grant select on table "public"."product_snapshot" to "service_role";

grant trigger on table "public"."product_snapshot" to "service_role";

grant truncate on table "public"."product_snapshot" to "service_role";

grant update on table "public"."product_snapshot" to "service_role";


